# Generated by Django 4.2.3 on 2023-08-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
