# Generated by Django 4.2.3 on 2023-08-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_faction_delete_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=10)),
                ('type', models.BigIntegerField()),
                ('faction_id', models.BigIntegerField()),
            ],
        ),
    ]
