# Generated by Django 4.2.3 on 2023-08-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='designation',
            field=models.CharField(max_length=50),
        ),
    ]
