# Generated by Django 4.2.3 on 2023-08-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_unit_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platoons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platoon_name', models.CharField(max_length=50)),
                ('platoon_image', models.CharField(max_length=100)),
                ('faction_id', models.BigIntegerField()),
            ],
        ),
    ]
