# Generated by Django 4.2.3 on 2023-09-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_platoons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='faction_id',
        ),
        migrations.AddField(
            model_name='unit',
            name='affiliation',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='authority',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='category',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='unit',
            name='combat',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='frame_sp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='leadership_points',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='morale',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='movement',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='numbers_bonus',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='propulsion_sp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='protection',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='weapons_sp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit',
            name='designation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rank',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.BigIntegerField(default=0),
        ),
    ]
