# Generated by Django 4.2.3 on 2023-09-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_remove_unit_faction_id_unit_affiliation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='frame_sp',
            new_name='frame_SP',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='propulsion_sp',
            new_name='propulsion_SP',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='weapons_sp',
            new_name='weapons_SP',
        ),
    ]
